# Generated by Django 4.2.4 on 2023-11-30 01:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('userID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rutUsuario', models.CharField(max_length=10)),
                ('tipoUsuario', models.CharField(choices=[('e', 'Entrevistador'), ('a', 'Analista')], max_length=20)),
                ('groups', models.ManyToManyField(related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='customuser_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCiudad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Entrevistado',
            fields=[
                ('entrevistadoID', models.AutoField(primary_key=True, serialize=False)),
                ('pNombreEntrevistado', models.CharField(max_length=255)),
                ('sNombreEntrevistado', models.CharField(blank=True, max_length=255, null=True)),
                ('pApellidoEntrevistado', models.CharField(max_length=255)),
                ('sApellidoEntrevistado', models.CharField(max_length=255)),
                ('rutEntrevistado', models.CharField(max_length=15)),
                ('fechaNacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('tipoTrabajo', models.CharField(choices=[('i', 'Independiente'), ('d', 'Dependiente')], default='i', max_length=1)),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], default='o', max_length=1)),
                ('contacto', models.CharField(blank=True, max_length=15)),
                ('direccionEntrevistado', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.ciudad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrevistado',
                'verbose_name_plural': 'Entrevistados',
                'db_table': 'entrevistado',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('productoID', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idProvincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProvincia', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entrevistado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.entrevistado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.producto')),
            ],
            options={
                'verbose_name': 'Produccion',
                'verbose_name_plural': 'Producciones',
                'db_table': 'produccion',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('empresaID', models.AutoField(primary_key=True, serialize=False)),
                ('rutEmpresa', models.CharField(max_length=15)),
                ('nombreEmpresa', models.CharField(max_length=255)),
                ('representanteLegal', models.CharField(max_length=255)),
                ('rutRepresentante', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('entrevistado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.entrevistado')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provinciaCiudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWeb.provincia'),
        ),
    ]
